package com.company.mateuszstempak;

//Every possible Items user can choose

public enum Items {
    TOMATO, CUCUMBER, LETTUCE, RUCOLA, BACON, CHEESE, BLUE_CHEESE, JALAPENO, PAPRIKA, BASIL, BASIL_PESTO,
    PARSLEY_PESTO, SALSA, KETCHUP, MUSTARD, MAYONNAISE, BARBECUE_SAUCE, BEEF_BURGER, CHICKEN_BURGER,
    FISH_BURGER, VEGE_BURGER, STANDARD_BREAD, DARK_BREAD, HEALTHY_BREAD, BROWN_RYE_BREAD, POTATO_CHIPS, FRENCH_FRIES,
    BELGIAN_FRIES, COFFEE, BEER, BARTENDER_DRINK
}
